In [1]:
import numpy as np

In [13]:
theta = np.array([-1, 1])
feature_matrix = np.array([[1, 2], [1, 2]])

In [14]:
theta

array([-1,  1])

In [18]:
feature_matrix.T

array([[1, 1],
       [2, 2]])

In [16]:
theta.shape

(2,)

In [17]:
feature_matrix.shape


(2, 2)

In [19]:
np.matmul(theta, feature_matrix.T)

array([1, 1])

In [1]:
## trials for perceptron_single_step_update

In [4]:
feature_vector = np.array([-0.3337126, -0.29643563, -0.09108841, -0.19144665, -0.4433603, -0.41607677,
                           0.19023474, -0.36549014, -0.29786766, -0.18079907])


In [5]:
label = 1

In [6]:
theta = np.array([-0.19710427, -0.45949196, -0.35979065,  0.4918851, 0.16452869, -0.34798097,
                  -0.19363107, 0.41122587, 0.39766789, -0.36110206])

In [7]:
theta_0= 0.05725409161055817

In [9]:
x = label * feature_vector

In [10]:
theta + x

array([-0.53081687, -0.75592759, -0.45087906,  0.30043845, -0.27883161,
       -0.76405774, -0.00339633,  0.04573573,  0.09980023, -0.54190113])

In [11]:
test = label * (np.dot(theta, feature_vector) + theta_0)

In [12]:
test

0.029384526705759556

In [2]:
## trials for pegasos_single_step_update

In [4]:
feature_vector = np.array([-0.01741128, -0.28910703, -0.01743757, -0.02991401, -0.44802031,  0.11041108,
                           0.22031343, 0.09792446, -0.36198037, 0.30282663])


In [5]:
label = -1

In [6]:
L = 0.14370935140156238

In [7]:
eta= 0.10827226418980795

In [8]:
theta_0 = -1.9002191645073507

In [9]:
theta = np.array([-0.09114152, -0.34035751, -0.10845961, 0.35010368, -0.39987072, 0.19206595,
         0.41684646, -0.01271288, 0.45866512, 0.34291557])

In [10]:
pegasos_loss = label * np.dot(theta, feature_vector)

In [11]:
pegasos_loss

-0.32016948741152873

In [14]:
prediction = np.dot(theta, feature_vector) + theta_0

In [15]:
prediction

-1.580049677095822