In [1]:
import numpy as np

In [13]:
theta = np.array([-1, 1])
feature_matrix = np.array([[1, 2], [1, 2]])

In [14]:
theta

array([-1,  1])

In [18]:
feature_matrix.T

array([[1, 1],
       [2, 2]])

In [16]:
theta.shape

(2,)

In [17]:
feature_matrix.shape


(2, 2)

In [19]:
np.matmul(theta, feature_matrix.T)

array([1, 1])